### ISSUE TITLE
OS X Mavericks PHP Apache -2.4.12 installation and configuration

### ISSUE THREAD

**Issue by ebonsi** [liip/php-osx#153]
Hello,
I am on OS X Mavericks 10.9.5 backup Client Server built from scratch (not the OS X Server). The native Apache/PHP/MySQL is running fine configured to run an e_commerce store. The native Apache version: Apache/2.2.29 got obsolete on SSL and I install the new Apache 2.4.12 on /usr/local. I tried to install php from the command line but it gave me some errors on make about Undefined symbols for architecture x86_64: and ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [libs/libphp5.bundle] Error 1. 

Any way, yours installed just fine on /usr/local.
My questions are;
- Does this php works with Apache Server 2.4.12 ?
- What are the configurations to load the php module on Apache Server 2.4.12 ? 
- Does any one tested this configuration and it is running ok?
  Thanks!
  <------>
  I am updating this post as at this time I finished configuring the Apache Server 2.4.12 I installed on /usr/local/apache-2.4.12 and it is working fine on port 8080 and SSL 8443 loading all my websites. Now I just need to point my php5 installation that is on the same directory to the new Apache Server so It can pick up the new Apache and not the old native one from OS X.  - How do I do that? Thanks!

**Comment by ebonsi** [comment]
So here is the latest update on this post. As you know I went ahead and installed php5 and it installed ok on Mavericks. However, this PHP have been configured to connect to the OS X native Apache version: Apache/2.2.29. That is ok for some folks. However, in my case, I am updating to Apache 2.4.12 because SSL become obsolete on 2.2.29. I configured 2.4.12 on port 8080 and SSL 8434 and everything is working just fine. All my websites are running with no problems. Now I am trying to configure apache 2.4.12 to connect to php and MySQL. I realized that this installation of php5 puts two files on apache 2.2.29 /other/ directory. I removed these files and the server fall back to my native php and that is good. 

Now I am configuring 2.4.12 and when I went to turn the module libphp5.so I am getting these logs and php5 is not starting.

httpd: Syntax error on line 157 of /usr/local/apache-2.4.12/conf/httpd.conf: Cannot load /usr/local/php5/libphp5.so into server: dlopen(/usr/local/php5/libphp5.so, 10): Symbol not found: _unixd_config\n  Referenced from: /usr/local/php5/libphp5.so\n  Expected in: /usr/local/apache-2.4.12/bin/httpd\n in /usr/local/php5/libphp5.so
- Do you have any clues of how to resolve this?
Thanks!

**Comment by chregu** [comment]
I assume you have to recompile the whole thing against apache 2.4, some things changed there, modules are not compatible between those two versions.

**Comment by ebonsi** [comment]
Thanks for your reply @chregu!
- Do you have some suggestions on ./configure \ compilation prefixes and applications against 2.4?

**Comment by chregu** [comment]
Maybe it's enough to just recompile the whole thing here. The only apache options in the script are here

https://github.com/liip/build-entropy-php/blob/5_4_mountainlion/build-php.pl#L60

which uses apxs to get the needed values
